# Generated by Django 3.2.23 on 2023-11-15 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('table_capicity', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=50)),
                ('reservation_email', models.EmailField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('number_people', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.IntegerField(choices=[(1, '09:00am - 11:00am'), (2, '11:00am - 13:00pm'), (3, '13:00pm - 15:00pm'), (4, '15:00pm - 17:00pm'), (5, '17:00pm - 21:00pm')], default=1)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.restauranttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
