# Generated by Django 3.2.23 on 2023-11-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttable',
            old_name='table_capicity',
            new_name='table_capacity',
        ),
    ]
