# Generated by Django 3.2.23 on 2023-11-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_table_capicity_restauranttable_table_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='table',
            new_name='reserved_table',
        ),
    ]
