# Generated by Django 3.2.23 on 2023-12-01 10:41

from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_table_reservation_reserved_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_people',
            field=models.IntegerField(validators=[reservation.models.validate_npeople]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(validators=[reservation.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_name',
            field=models.CharField(max_length=20, validators=[reservation.models.validate_name]),
        ),
    ]
